version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    depends_on:
      - database
  frontend:
    volumes:
      - ./frontend/src:/frontend/src
    build:
      context: ./frontend
    environment:
      - ENV=${ENV}
      - WATCHPACK_POLLING=true
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  db:
